Gems test
trufanovnik/trainee-planner pull request #13
Opened 2023-08-07 00:59 UTC by trufanovnik

## Task
add gems for test
## Change proposed in this pull request:
- добавил гем Rspec и выполнил базовую настройку
- добавил гем database cleaner и выполнил настройку
- добавил гем shoulda matchers и выполнил настройку
- добавил гем simplecov и выполнил настройку

2023-08-07 10:42 UTC, DariaAres submitted a review, later dismissed

2023-08-07 10:59 UTC, TsikhanauDzmitry requested changes

2023-08-07 11:05 UTC, trufanovnik commented on Gemfile
> +  gem 'rspec-rails', '~> 6.0.0'
> Почему этот гем был добавлен в данное окружение?

так указано в доке

2023-08-07 11:08 UTC, trufanovnik commented on Gemfile
> +  #Set of gems containing strategies for cleaning your database in Ruby [https://github.com/DatabaseCleaner/database_cleaner]
исправил

2023-08-07 11:09 UTC, trufanovnik commented on Gemfile
> +  #Clean your Redis databases with Database Cleaner. [https://github.com/DatabaseCleaner/database_cleaner-redis]
исправил

2023-08-07 11:10 UTC, DariaAres approved these changes, later dismissed

2023-08-07 13:52 UTC, trufanovnik commented on Gemfile
> +  gem 'rspec-rails', '~> 6.0.0'
> Почему этот гем был добавлен в данное окружение?

в группу dev добавлять необязательно, но в противном случае перед задачами rake нужно указывать RAILS_ENV=test

2023-08-09 16:19 UTC, TsikhanauDzmitry reviewed
Зарезолвих конфликты и сохрани такие красивые коммиты

2023-08-09 16:37 UTC, dasha-sync approved these changes

2023-08-09 17:27 UTC, TsikhanauDzmitry approved these changes

2023-08-09 17:28 UTC, merged