Cicd
trufanovnik/trainee-planner pull request #19
Opened 2023-08-15 11:37 UTC by trufanovnik

## Task:
Добавить CI/CD с тестами и рубокоп
## Change proposed in this pull request:
- Добавил CI/CD 
- Установил руби 3.1.4 для корректной работы ruby/setup-ruby
- Исправил ошибки рубокоп

2023-08-15 12:10 UTC, DariaAres submitted a review, later dismissed

2023-08-15 12:35 UTC, DariaAres approved these changes, later dismissed

2023-08-16 10:53 UTC, TsikhanauDzmitry commented
Что с названием PR?

2023-08-16 10:54 UTC, TsikhanauDzmitry requested changes

2023-08-16 10:54 UTC, TsikhanauDzmitry commented on .github/workflows/rspec.yml
> +        options: --entrypoint redis-server
Вообще не уверен, что это должно так быть...

2023-08-16 11:53 UTC, trufanovnik commented on .github/workflows/rspec.yml
> +        options: --entrypoint redis-server
исправил

2023-08-16 11:57 UTC, DariaAres approved these changes

2023-08-18 07:31 UTC, TsikhanauDzmitry approved these changes

2023-08-18 07:37 UTC, merged