Add bootstrap
trufanovnik/trainee-planner pull request #8
Opened 2023-08-01 11:15 UTC by trufanovnik

## Task: 
add bootstrap
## Change proposed in this pull request:
- Добавил гем cssbundling-rails
- Запустил bin/rails css:install:bootstrap для установки bootstrap
- Добавил гем jsbundling-rails
- Запустил bin/rails javascript:install:esbuild для установки esbuild
- Настройка выполнялась согласно этому гайду https://mixandgo.com/learn/ruby-on-rails/how-to-install-bootstrap

2023-08-01 11:54 UTC, DariaAres submitted a review, later dismissed

2023-08-08 11:15 UTC, trufanovnik commented on Gemfile
> +gem "jsbundling-rails", "~> 1.1"
Исправил.

2023-08-08 11:19 UTC, DariaAres approved these changes, later dismissed

2023-08-08 11:25 UTC, TsikhanauDzmitry requested changes

2023-08-08 11:25 UTC, TsikhanauDzmitry commented on .env
Этого файла тут быть не должно

2023-08-08 11:25 UTC, TsikhanauDzmitry commented on bin/dev
Зачем это было добавлено?

2023-08-08 11:25 UTC, TsikhanauDzmitry commented on app/assets/builds/.keep
За что отвечают `.keep` файлы?

2023-08-08 11:25 UTC, TsikhanauDzmitry commented on Procfile.dev
Зачем этот файл был добавлен?

2023-08-08 11:26 UTC, TsikhanauDzmitry commented
@trufanovnik таких ([run bundle add jsbundling-rails](https://github.com/trufanovnik/trainee-planner/pull/8/commits/d1b1d24eccac8e6df1fd5f4db3299b5f00fffcf6)) коммитов быть не должно

2023-08-08 14:56 UTC, trufanovnik commented on .env
исправил

2023-08-08 15:07 UTC, trufanovnik commented on bin/dev
скрипт проверяет установлен ли гем foreman и запускает Procfile.dev 
в Procfile мы проверяем обновились ли наши файлы css и запускаем сервер.

2023-08-08 15:10 UTC, trufanovnik commented on Procfile.dev
в этом скрипте мы запускаем сервер, а также запускаем процесс для отслеживания изменений в файлах CSS и компиляции их в один файл, запускаем процесс для сборки и оптимизации файлов JavaScript.

2023-08-08 15:12 UTC, trufanovnik commented
> @trufanovnik таких ([run bundle add jsbundling-rails](https://github.com/trufanovnik/trainee-planner/pull/8/commits/d1b1d24eccac8e6df1fd5f4db3299b5f00fffcf6)) коммитов быть не должно

исправлено на `add gem jsbundling-rails`

2023-08-08 16:28 UTC, trufanovnik commented on app/assets/builds/.keep
нужны для того, чтобы гит не игнорировал пустые папки. Эта папка пустая, но в ней могут храниться сборки JS в дальнейшем.

2023-08-08 16:32 UTC, DariaAres approved these changes, later dismissed

2023-08-09 16:17 UTC, TsikhanauDzmitry submitted a review, later dismissed

2023-08-10 08:26 UTC, DariaAres approved these changes

2023-08-10 08:38 UTC, TsikhanauDzmitry approved these changes

2023-08-10 08:39 UTC, merged